# Generated by Django 2.1 on 2020-04-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groundcoverdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(blank=True, max_length=255)),
                ('latitude', models.SmallIntegerField()),
                ('longitude', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
