# Generated by Django 3.0.5 on 2020-05-05 19:28

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groundcoverdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(blank=True, max_length=255)),
                ('latitude', models.SmallIntegerField()),
                ('longitude', models.SmallIntegerField()),
                ('collectionpoint', djgeojson.fields.PointField(null=True, verbose_name='Collection Point')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
