# Generated by Django 3.0.3 on 2020-06-26 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groundcoverdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(blank=True, max_length=255)),
                ('collectionpoint', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Collection Point')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fgcc_value', models.DecimalField(blank=True, decimal_places=7, max_digits=10)),
            ],
        ),
    ]
