# Generated by Django 3.0.5 on 2020-05-06 01:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samplepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sampleloc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
