# Generated by Django 3.0.5 on 2020-04-27 01:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundcoverdoc',
            name='collectionpoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Collection Point'),
        ),
    ]
