# Generated by Django 3.0 on 2020-07-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundcoverdoc',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_planting_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_planting_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_species_1',
            field=models.CharField(choices=[('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Vicia villosa'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_species_2',
            field=models.CharField(blank=True, choices=[('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Vicia villosa'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_species_3',
            field=models.CharField(blank=True, choices=[('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Vicia villosa'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_species_4',
            field=models.CharField(blank=True, choices=[('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Vicia villosa'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_termination_date',
            field=models.DateField(blank=True, default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='crop_prior',
            field=models.CharField(choices=[('CORN', 'Corn'), ('CORN_SILAGE', 'Corn silage'), ('SOY_BEANS', 'Soy beans'), ('SMALL_GRAIN', 'Small grain'), ('CANNING_CROP', 'Canning crop'), ('POTATOES', 'Potatoes'), ('DRY_BEANS', 'Dry beans'), ('SUGAR_BEETS', 'Sugar beets'), ('PREVENT_PLANT', 'Prevent plant'), ('OTHER', 'Other')], default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='seeding_method',
            field=models.CharField(choices=[('DRILL', 'Drill'), ('BROADCAST', 'Broadcast'), ('BROADCAST_INCORPORATION', 'Broadcast plus incorporation'), ('AERIAL', 'Aerial'), ('MANURE_SLURRY', 'Manure slurry'), ('OTHER', 'Other')], default='', max_length=55),
            preserve_default=False,
        ),
    ]
