# Generated by Django 3.0.5 on 2020-04-27 18:11

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0002_groundcoverdoc_collectionpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='collectionpoint',
            field=djgeojson.fields.PointField(null=True, verbose_name='Collection Point'),
        ),
    ]
