# Generated by Django 2.2 on 2020-05-06 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0002_samplepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='collectionpoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Collection Point'),
        ),
    ]
