# Generated by Django 3.0 on 2020-07-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0002_auto_20200714_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundcoverdoc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groundcoverdoc',
            name='locname',
        ),
    ]
