# Generated by Django 3.0 on 2020-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0004_auto_20200718_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundcoverdoc',
            name='cover_crop_interseeded',
            field=models.BooleanField(null=True, verbose_name='Was the cover crop intereseeded?'),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='crop_posterior',
            field=models.CharField(blank=True, choices=[('CORN', 'Corn'), ('CORN_SILAGE', 'Corn silage'), ('SOY_BEANS', 'Soy beans'), ('SMALL_GRAIN', 'Small grain'), ('CANNING_CROP', 'Canning crop'), ('POTATOES', 'Potatoes'), ('DRY_BEANS', 'Dry beans'), ('SUGAR_BEETS', 'Sugar beets'), ('PREVENT_PLANT', 'Prevent plant'), ('OTHER', 'Other')], max_length=25, verbose_name='Cash crop to be planted after'),
        ),
        migrations.AddField(
            model_name='groundcoverdoc',
            name='photo_taken_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_planting_rate',
            field=models.FloatField(help_text='in pounds per acre'),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_species_1',
            field=models.CharField(choices=[('None', '----------'), ('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Hairy Vetch (Vicia villosa)'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_species_2',
            field=models.CharField(blank=True, choices=[('None', '----------'), ('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Hairy Vetch (Vicia villosa)'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_species_3',
            field=models.CharField(blank=True, choices=[('None', '----------'), ('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Hairy Vetch (Vicia villosa)'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_species_4',
            field=models.CharField(blank=True, choices=[('None', '----------'), ('ALFALFA', 'Alfalfa (Medicago sativa)'), ('ANNUAL_RYE', 'Annual Rye (Lolium multiflorum'), ('BUCKWHEAT', 'Buckweat (Fagopyrum esculentum)'), ('CAMELINA', 'Camelina (Camelina sativa)'), ('CEREAL_RYE', 'Cereal Rye (Secale cereale)'), ('COWPEAS', 'Cowpeas (Vigna unguiculata)'), ('CRIMSON_CLOVER', 'Crimson Clover (Trifolium incarnatum)'), ('HAIRY_VETCH', 'Hairy Vetch (Vicia villosa)'), ('MUSTARDS', 'Mustartds (Brassicaceae)'), ('OATS', 'Oats (Avena sativa)'), ('PENNYCRESS', 'Pennycress (Thlaspi arvense)'), ('RADISH', 'Radish (Raphanus sativus)'), ('RAPESEED', 'Rapeseed (Brassica napus)'), ('RED_CLOVER', 'Red Clover (Trifolium pratense)'), ('SUNN_HEMP', 'Sunn Hemp (Crotalaria juncea)'), ('TURNIP', 'Turnip (Brassica rapa var. rapa)'), ('WHITE_CLOVER', 'White Clover (Trifolium repens)'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='crop_prior',
            field=models.CharField(blank=True, choices=[('CORN', 'Corn'), ('CORN_SILAGE', 'Corn silage'), ('SOY_BEANS', 'Soy beans'), ('SMALL_GRAIN', 'Small grain'), ('CANNING_CROP', 'Canning crop'), ('POTATOES', 'Potatoes'), ('DRY_BEANS', 'Dry beans'), ('SUGAR_BEETS', 'Sugar beets'), ('PREVENT_PLANT', 'Prevent plant'), ('OTHER', 'Other')], max_length=25, verbose_name='Cash crop planted prior'),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='seeding_method',
            field=models.CharField(choices=[('DRILL', 'Drill'), ('BROADCAST', 'Broadcast'), ('BROADCAST_INCORPORATION', 'Broadcast plus incorporation'), ('AERIAL', 'Aerial'), ('MANURE_SLURRY', 'Manure slurry'), ('OTHER', 'Other')], max_length=55, verbose_name='Cover crop seeding method'),
        ),
    ]
