# Generated by Django 3.0 on 2020-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0004_auto_20200506_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
