# Generated by Django 3.0 on 2020-08-11 00:31

from django.db import migrations, models
import exploring_soils.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0005_auto_20200718_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_interseeded',
            field=models.BooleanField(null=True, verbose_name='Was the cover crop interseeded?'),
        ),
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='image',
            field=models.ImageField(storage=exploring_soils.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
