# Generated by Django 3.0 on 2020-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0005_auto_20200507_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundcoverdoc',
            name='fgcc_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
