# Generated by Django 3.0 on 2020-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0006_auto_20200810_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundcoverdoc',
            name='cover_crop_termination_date',
            field=models.DateField(null=True),
        ),
    ]
