# Generated by Django 3.0 on 2020-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanopy', '0007_auto_20200810_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundcoverdoc',
            name='location_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
