#!/bin/bash

NAME="exploring_soils"
DIR=/home/ubuntu/exploring_soils
USER=ubuntu
GROUP=ubuntu
WORKERS=3
BIND=unix:/home/ubuntu/exploring_soils/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=exploring_soils.settings
DJANGO_WSGI_MODULE=exploring_soils.wsgi
LOG_LEVEL=debug

cd $DIR
source ./myvenv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ./myvenv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-