# Generated by Django 4.2.15 on 2024-10-02 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exploring_soils.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wisccc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signup_timestamp", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(blank=True, max_length=250)),
                ("last_name", models.CharField(blank=True, max_length=250)),
                (
                    "institution",
                    models.TextField(
                        null=True,
                        verbose_name="What institution does the researcher belong to?",
                    ),
                ),
                (
                    "agreement_doc",
                    models.FileField(
                        blank=True,
                        storage=exploring_soils.storage_backends.WiscCCResearcherDocStorage(),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(null=True)),
                (
                    "download_count",
                    models.IntegerField(
                        default=0,
                        verbose_name="Count of times the researcher has downloaded data.",
                    ),
                ),
                (
                    "last_download_timestamp",
                    models.DateTimeField(
                        null=True,
                        verbose_name="Timestamp of when the researcher last download the data.",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="Is the user approved for downloading data?",
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        null=True,
                        verbose_name="When the user was approved. Download permission expires after one year.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (("approved_researcher", "Approved researcher"),),
            },
        ),
    ]
