# Generated by Django 2.1 on 2020-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='finished_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Novel'), (2, 'Non-Fiction'), (3, 'Biography'), (4, 'Short story'), (5, 'Graphic novel'), (6, 'Other')]),
        ),
    ]
