# Generated by Django 2.1 on 2018-09-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=30, unique=True)),
                ('lower_left_corner', models.FloatField()),
                ('upper_left_corner', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('plot_cnt_wide', models.PositiveSmallIntegerField()),
                ('plot_cnt_long', models.PositiveSmallIntegerField()),
                ('plot_sz_wide', models.FloatField()),
                ('plot_sz_long', models.FloatField()),
                ('alley_dist_wide', models.FloatField(null=True)),
                ('alley_dist_long', models.FloatField(null=True)),
                ('metric', models.BooleanField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rep',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reps', to='plotter.Study'),
        ),
    ]
