# Generated by Django 2.1 on 2018-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='block',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
