# Generated by Django 2.1 on 2018-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_rep_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='lower_left_corner',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='upper_left_corner',
        ),
        migrations.AddField(
            model_name='rep',
            name='lower_left_corner_x',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='rep',
            name='lower_left_corner_y',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='rep',
            name='upper_left_corner_x',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='rep',
            name='upper_left_corner_y',
            field=models.FloatField(default=1),
        ),
    ]
