# Generated by Django 4.2.15 on 2024-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plotter", "0003_auto_20180914_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rep",
            name="lower_left_corner_x",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rep",
            name="lower_left_corner_y",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rep",
            name="upper_left_corner_x",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="rep",
            name="upper_left_corner_y",
            field=models.FloatField(default=0),
        ),
    ]
