# Generated by Django 2.1 on 2020-02-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='author',
        ),
        migrations.AddField(
            model_name='mileage',
            name='rider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
