# Generated by Django 2.1 on 2020-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0002_auto_20200219_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
