# Generated by Django 2.1 on 2020-02-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0003_auto_20200219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
