# Generated by Django 2.1 on 2020-02-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0005_auto_20200220_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='mileage',
            field=models.FloatField(null=True),
        ),
    ]
