# Generated by Django 2.1 on 2020-02-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0006_auto_20200220_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='bike_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Blue Trek'), (2, 'Red Trek'), (3, 'Takara'), (4, 'Fuji'), (6, 'Other')]),
        ),
    ]
