# Generated by Django 2.1 on 2020-03-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikemileage', '0008_bicycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='bike_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mileage', to='bikemileage.Bicycle'),
        ),
    ]
